"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['quickConnect.py']
DATA_FILES = ['connect_ssh.scpt','icon.png']
OPTIONS = {'argv_emulation': True,
		   'compressed': True,
		   'includes': ['sip', 'PyQt4._qt'],
		   'optimize': '2',
		   'strip': True
		   }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
